Fixed up messaging a little and restructured the child shell initfile to make adding stuff easier.

diff --git a/kubesh b/kubesh
--- a/kubesh
+++ b/kubesh
@@ -149,7 +149,7 @@ function __select_context {
   __print_context_list
   read -s -N 1 -p "Select context: " choice
   printf "\n"
-  local err_msg="ERROR: choice must be an integer in the range 1..${#contexts[@]}"
+  local err_msg="Error: choice must be an integer in the range 1..${#contexts[@]}"
   case $choice in
     ''|*[!0-9]*)
       echo $err_msg
@@ -225,7 +225,7 @@ function prompt {
         __prompt_set
         ;;
       *)
-        echo "ERROR: unrecognized subcommand $1"
+        echo "Error: unrecognized subcommand $1"
         __print_prompt_commands
         ;;
     esac
@@ -359,12 +359,20 @@ function help {
 # Check to make sure necessary commands are installed.
 #
 if ! command -v kubectl > /dev/null 2>&1; then
-  echo "ERROR: kubesh requires kubectl (https://kubernetes.io/docs/tasks/kubectl/install/)"
+  echo "Error: kubesh requires kubectl (https://kubernetes.io/docs/tasks/kubectl/install/)"
   exit 1
 fi
 if ! command -v sed > /dev/null 2>&1; then
-  echo "ERROR: kubesh requires the sed program (https://www.gnu.org/software/sed/manual/sed.html)"
+  echo "Error: kubesh requires the sed program (https://www.gnu.org/software/sed/manual/sed.html)"
   exit 1
+fi
+
+#
+# Determines below whether we can watch the kubectl config for changes.
+#
+export inotify=false
+if command -v inotifywait > /dev/null 2>&1; then
+  inotify=true
 fi
 
 #
@@ -373,7 +381,7 @@ fi
 set +e
 current_context=$(kubectl config current-context 2>&1)
 if [ $? != 0 ]; then
-  echo "ERROR: couldn't read current kubectl context (do you have one?)"
+  echo "Error: couldn't read current kubectl context (do you have one?)"
   exit 1
 fi
 set -e
@@ -397,7 +405,7 @@ while getopts hn opt; do
       prompt_on=false
       ;;
     *)
-      echo "ERROR: Unknown option '${opt}'"
+      echo "Error: Unknown option '${opt}'"
       cli_help 1
       ;;
   esac
@@ -428,4 +436,18 @@ export -f help
 #
 # Invoke the shell with exec so its interactive and PS1 gets set.
 #
-exec bash --init-file <(echo '. ~/.bashrc; export old_prompt=$PS1; echo ${kubesh_welcome}; if $prompt_on; then PS1="(${active_context}) $old_prompt"; fi')
+exec bash --init-file <(cat << 'EOF'
+  . ~/.bashrc
+  export old_prompt=$PS1
+  echo ${kubesh_welcome}
+  if $prompt_on; then
+    PS1="(${active_context}) $old_prompt"
+  fi
+  if ! $inotify; then
+    echo "Warning: inotifywait not installed; changes to the kubectl context made"
+    echo "outside kubesh will not be noticed by the shell. Install the inotify-tools"
+    echo "package then restart kubesh if you want the shell to pick up changes."
+  fi
+  printf "\n"
+EOF
+)
