Handle the temp file sort of portably; moved the existing instance check higher.

diff --git a/kubesh b/kubesh
--- a/kubesh
+++ b/kubesh
@@ -16,7 +16,7 @@
 
 set -ueo pipefail
 
-export kubesh_version="0.2.2"
+export kubesh_version="0.3.0"
 
 #
 # Only called when the -h options is passed on the command line, not really
@@ -25,8 +25,8 @@ export kubesh_version="0.2.2"
 function __cli_help {
 cat << EOF
 NAME
-  kubesh - sets up a shell environment for kubernetes kubectl tool with a
-  number of useful commands.
+  kubesh ${kubesh_version} - sets up a shell environment for kubernetes
+  kubectl tool with several convenient context management functions.
 
 SYNOPSIS
   kubesh [-h] [-n]
@@ -119,7 +119,7 @@ function __print_context {
 #
 function __switch_context {
   if $inotify; then
-    touch /tmp/.kubesh_config_changing
+    touch ${tempdir}/.kubesh_config_changing
   fi
   kubectl config use-context $1
   active_context=$(kubectl config current-context)
@@ -363,16 +363,27 @@ function help {
 # the kubectl config is changed outside the shell
 #
 function __on_config_changed {
-  if [ ! -f /tmp/.kubesh_config_changing ]; then
+  if [ ! -f ${tempdir}/.kubesh_config_changing ]; then
     current_context=$(kubectl config current-context 2>&1)
     if [ "$current_context" != "$active_context" ]; then
       active_context=$current_context
       kill -n 14 $$
     fi
   else
-    rm /tmp/.kubesh_config_changing
+    rm ${tempdir}/.kubesh_config_changing
   fi
 }
+
+#
+# Let's not run inside ourself
+#
+set +u
+if [ ! -z "$kubesh_pid" ]; then
+  echo "Error: kubesh is already running"
+  exit 1
+fi
+set -u
+export kubesh_pid=$$
 
 #
 # Check to make sure necessary commands are installed.
@@ -399,6 +410,7 @@ fi
 #
 # These exports maintain state that is needed in the child shell
 #
+export tempdir=${TMPDIR-/tmp}
 export active_context
 export prompt_on=true
 export kubesh_welcome="kubesh ${kubesh_version} (type 'help' for more information)"
@@ -420,17 +432,6 @@ while getopts hn opt; do
       ;;
   esac
 done
-
-#
-# Let's not run inside ourself
-#
-set +u
-if [ ! -z "$kubesh_pid" ]; then
-  echo "Error: kubesh is already running"
-  exit 1
-fi
-set -u
-export kubesh_pid=$$
 
 #
 # These have to be exported so they are available to be called when commands are
